name: Build, Scan, and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest .

    - name: Download Trivy DB
      run: |
        mkdir -p ~/.cache/trivy/db
        trivy --download-db-only

    - name: Scan Docker image for vulnerabilities with Trivy
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
        severity: HIGH,CRITICAL
        format: 'table'
        trivy-db: ~/.cache/trivy/db  # Utiliser la base de données locale téléchargée

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
