name: Build, Scan, and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Utilisation de l'environnement Ubuntu pour GitHub Actions

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest .

    - name: Install Trivy
      run: |
        # Update and install dependencies
        sudo apt-get update
        sudo apt-get install -y wget
        # Download and install Trivy
        wget https://github.com/aquasecurity/trivy/releases/download/v0.29.2/trivy_0.29.2_Linux-64bit.deb
        sudo dpkg -i trivy_0.29.2_Linux-64bit.deb

    - name: Download Trivy DB (Vulnerability Database)
      run: |
        # Create cache folder and download the vulnerability DB
        mkdir -p ~/.cache/trivy/db
        trivy --download-db-only

    - name: Scan Docker image for vulnerabilities with Trivy
      run: |
        # Scan the image with Trivy
        trivy image ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest --severity HIGH,CRITICAL --format table

    - name: Push Docker image to GitHub Packages
      run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest