name: Build, Scan, and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest .

    - name: Scan Docker image for vulnerabilities with Trivy
      uses: aquasecurity/trivy-action@v0.4.0
      with:
        image: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
